"""Independence of trust signals in CanAssumeRole resolution.

Verifies that named-principal and root-trust are evaluated as
independent candidate generators feeding one shared, signal-blind
permission-side confirmation -- i.e., neither signal short-circuits
the other.
"""

from cloud_path_mapper.analysis.graph_builder import AttackGraphBuilder

ACCT = "666677778888"
X = f"arn:aws:iam::{ACCT}:user/identity-x"
OTHER = f"arn:aws:iam::{ACCT}:user/other-user"
TARGET = f"arn:aws:iam::{ACCT}:role/TargetRole"
ROOT = f"arn:aws:iam::{ACCT}:root"


def _user(name, arn, inline_policies=None):
    return {
        "type": "user",
        "name": name,
        "arn": arn,
        "groups": [],
        "attached_policy_arns": [],
        "inline_policies": inline_policies or {},
    }


def _role(name, trust_stmts):
    return {
        "type": "role",
        "name": name,
        "arn": TARGET if name == "TargetRole" else f"arn:aws:iam::{ACCT}:role/{name}",
        "trust_policy": {"Statement": trust_stmts},
        "attached_policy_arns": [],
        "inline_policies": {},
    }


WILDCARD_GRANT = {
    "BroadAssume": {
        "Statement": [
            {
                "Effect": "Allow",
                "Action": "sts:AssumeRole",
                "Resource": f"arn:aws:iam::{ACCT}:role/*",
            }
        ]
    }
}


def test_named_principal_satisfied_by_wildcard_grant():
    """Trust names identity-x only; x holds a wildcard role/* grant.

    The single signal-blind grant check must accept the wildcard grant
    and create the edge with basis=named-principal.
    """
    iam = {
        "account_id": ACCT,
        "users": [_user("identity-x", X, inline_policies=WILDCARD_GRANT)],
        "roles": [
            _role(
                "TargetRole",
                [{"Effect": "Allow", "Principal": {"AWS": X}, "Action": "sts:AssumeRole"}],
            )
        ],
        "groups": [],
        "instance_profiles": [],
        "policies": {},
    }
    builder = AttackGraphBuilder(iam, {"buckets": []}, {"instances": []})
    g = builder.build()

    data = g.get_edge_data(X, TARGET)
    assert data is not None, "edge missing: wildcard grant failed to satisfy named trust"
    assert data["basis"] == "named-principal"
    assert not [f for f in builder.informational_findings if f["type"] == "TrustedButNoGrant"]


def test_both_signals_present_label_takes_named_precedence():
    """Trust names x AND trusts root; x has a wildcard grant.

    Both signals qualify the same pair; the edge is created once and
    the basis label reflects named-principal precedence. Evaluation
    itself was unified (single grant check), so this pins the labeling
    behavior rather than any branching semantics.
    """
    iam = {
        "account_id": ACCT,
        "users": [_user("identity-x", X, inline_policies=WILDCARD_GRANT)],
        "roles": [
            _role(
                "TargetRole",
                [
                    {"Effect": "Allow", "Principal": {"AWS": X}, "Action": "sts:AssumeRole"},
                    {"Effect": "Allow", "Principal": {"AWS": ROOT}, "Action": "sts:AssumeRole"},
                ],
            )
        ],
        "groups": [],
        "instance_profiles": [],
        "policies": {},
    }
    builder = AttackGraphBuilder(iam, {"buckets": []}, {"instances": []})
    g = builder.build()

    data = g.get_edge_data(X, TARGET)
    assert data is not None
    assert data["basis"] == "named-principal"
    # Exactly one finding-free edge: no TrustedButNoGrant despite the
    # pair having been generated by two signals.
    assert not [f for f in builder.informational_findings if f["type"] == "TrustedButNoGrant"]


def test_signals_evaluated_independently_across_different_pairs():
    """Named signal fails for other-user while root signal succeeds for x.

    Trust names OTHER specifically AND ALSO trusts root. other-user has
    no grant at all -> TrustedButNoGrant. identity-x (unnamed) holds a
    wildcard grant -> valid edge via root-trust. If signals short-
    circuited per-pair or per-role, one of these outcomes would vanish.
    """
    iam = {
        "account_id": ACCT,
        "users": [
            _user("other-user", OTHER),
            _user("identity-x", X, inline_policies=WILDCARD_GRANT),
        ],
        "roles": [
            _role(
                "TargetRole",
                [
                    {"Effect": "Allow", "Principal": {"AWS": OTHER}, "Action": "sts:AssumeRole"},
                    {"Effect": "Allow", "Principal": {"AWS": ROOT}, "Action": "sts:AssumeRole"},
                ],
            )
        ],
        "groups": [],
        "instance_profiles": [],
        "policies": {},
    }
    builder = AttackGraphBuilder(iam, {"buckets": []}, {"instances": []})
    g = builder.build()

    # Named-but-ungrantable relationship recorded, NOT an edge.
    findings = [f for f in builder.informational_findings if f["type"] == "TrustedButNoGrant"]
    assert len(findings) == 1
    assert findings[0]["identity"] == OTHER
    assert not g.has_edge(OTHER, TARGET)

    # Independent root-trust resolution still created x's edge.
    data = g.get_edge_data(X, TARGET)
    assert data is not None
    assert data["basis"] == "root-trust"


if __name__ == "__main__":
    test_named_principal_satisfied_by_wildcard_grant()
    test_both_signals_present_label_takes_named_precedence()
    test_signals_evaluated_independently_across_different_pairs()
    print("ALL DUAL-SIGNAL TRUST TESTS PASS")
